// src/components/NavbarComponent.vue
<script setup lang="ts">
import { useAuth } from '@/composables/useAuth'
import Logo from '@/images/linux.svg'
import Button from '@/components/ButtonComponent.vue'
import NavbarLinks from '@/composables/navLinks'

const { isAuthenticated, logout } = useAuth()

const handleLogout = () => {
  logout()
}
</script>

<template>
  <div class="container flex items-center justify-between py-4">
    <!-- logo section-->
    <div class="flex items-center gap-1">
      <a href="/">
        <img :src="Logo" alt="Logo" class="w-[60px]" />
      </a>
      <p class="text-xl font-bold transition duration-300 select-none hover:text-[#fcc61d]">Notifier</p>
    </div>

    <!-- link section-->
    <div class="hidden md:block">
      <ul class="flex gap-3 xl:gap-7">
        <li v-for="link in NavbarLinks" :key="link.id">
          <component
            :is="link.external ? 'a' : 'router-link'"
            :href="link.external ? link.to : null"
            :to="!link.external ? link.to : null"
            rel="noopener noreferrer"
            class="cursor-pointer uppercase hover:text-[#fcc61d] xl:text-base"
            >{{ link.label }}</component
          >
        </li>
        <li v-if="isAuthenticated">
          <router-link to="/dashboard" class="uppercase hover:text-[#fcc61d] xl:text-base">Dashboard</router-link>
        </li>
      </ul>
    </div>

    <!-- button section-->
    <div class="flex items-center gap-3">
      <div v-if="!isAuthenticated">
        <router-link to="/login" class="primary-btn cursor-pointer text-lg">Log In</router-link>
      </div>
      <div v-else class="flex items-center gap-3">
        <Button @click="handleLogout" type="button" label="Log out" class="primary-btn cursor-pointer text-lg" />
      </div>
    </div>
  </div>
</template>

// src/components/Navbar/navbar.tsx
import NavbarLinks from "../../constants/navLinks";
import { useAuthStore } from "../../store";
import { Link, useNavigate } from "react-router";
import Logo from "/assets/images/linux.svg";
import { Button } from "../Button";

export const NavbarComponent = () => {
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated);
  const logout = useAuthStore((s) => s.logout);
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate("/");
  };

  return (
    <div className="container flex items-center justify-between py-4">
      {/* logo section */}
      <div className="flex items-center gap-1">
        <Link to="/">
          <img src={Logo} alt="Logo" className="w-15" />
        </Link>
        <p className="text-xl font-bold transition duration-300 select-none hover:text-[#fcc61d]">
          Notifier
        </p>
      </div>

      {/* link section */}
      <div className="hidden md:block">
        <ul className="flex gap-3 xl:gap-15">
          {NavbarLinks.map((link) => (
            <li key={link.id}>
              {link.external ? (
                <a
                  href={link.to}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="cursor-pointer uppercase hover:text-[#fcc61d] xl:text-base"
                >
                  {link.label}
                </a>
              ) : (
                <Link
                  to={link.to}
                  className="cursor-pointer uppercase hover:text-[#fcc61d] xl:text-base"
                >
                  {link.label}
                </Link>
              )}
            </li>
          ))}

          {isAuthenticated && (
            <li>
              <Link
                to="/dashboard"
                className="uppercase hover:text-[#fcc61d] xl:text-base"
              >
                Dashboard
              </Link>
            </li>
          )}
        </ul>
      </div>

      {/* button section */}
      <div className="flex items-center gap-3">
        {!isAuthenticated ? (
          <Link to="/login" className="primary-btn cursor-pointer text-lg">
            Log In
          </Link>
        ) : (
          <Button
            onClick={handleLogout}
            type="button"
            label="Log out"
            className="primary-btn cursor-pointer text-lg"
          />
        )}
      </div>
    </div>
  );
};
