// src/components/Button/button.tsx
interface Props {
  type?: "submit" | "button" | "reset";
  label: string;
  className?: string;
  disabled?: boolean;
  onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
}

export const Button = ({
  type = "submit",
  label,
  className,
  disabled,
  onClick,
}: Props) => {
  return (
    <button
      type={type}
      className={className}
      disabled={disabled}
      onClick={onClick}
    >
      {label}
    </button>
  );
};

// src/components/ButtonComponent.vue
<script setup lang="ts">
import { defineProps } from 'vue'

const props = defineProps<{
  type?: 'submit' | 'button' | 'reset'
  label: string
  class?: string
  disabled?: boolean
}>()

const buttonType = props.type ?? 'submit'
</script>

<template>
  <button :type="buttonType" :class="props.class" :disabled="props.disabled">{{ props.label }}</button>
</template>
