// src/components/Input/input.tsx
interface Props {
  value?: string | number;
  id?: string;
  name?: string;
  type?: string;
  placeholder?: string;
  required?: boolean;
  disabled?: boolean;
  className?: string;
  onChange?: (value: string) => void;
}

export const InputComponent = ({
  value,
  id,
  name,
  type = "text",
  placeholder,
  required,
  disabled,
  className,
  onChange,
}: Props) => {
  return (
    <input
      value={value}
      id={id}
      name={name}
      type={type}
      placeholder={placeholder}
      required={required}
      disabled={disabled}
      className={className}
      onChange={(e) => onChange?.(e.target.value)}
    />
  );
};

// src/components/InputComponent.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  modelValue?: string | number
  id?: string
  name?: string
  type?: string
  placeholder?: string
  required?: boolean
  disabled?: boolean
  class?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const inputValue = computed({
  get: () => props.modelValue || '',
  set: (value: string) => emit('update:modelValue', value)
})

const inputType = props.type || 'text'
</script>

<template>
  <input
    :id="props.id"
    :name="props.name"
    :type="inputType"
    :placeholder="props.placeholder"
    :required="props.required"
    :disabled="props.disabled"
    :class="props.class"
    v-model="inputValue"
  />
</template>
