// src/components/LoginComponent.vue
<script setup lang="ts">
import ButtonComponent from './ButtonComponent.vue'
import InputComponent from './InputComponent.vue'
import LoginImage from '@/images/hero.jpg'

defineOptions({
  name: 'LoginComponent',
})

// variables to use in the child (loginview)
const props = defineProps<{
  email: string
  password: string
  isLoading?: boolean
  errorMessage?: string
}>()
const emit = defineEmits<{
  'update:email': [value: string]
  'update:password': [value: string]
  submit: []
}>()
const handleSubmit = () => {
  emit('submit')
}
const updateEmail = (value: string) => {
  emit('update:email', value)
}
const updatePassword = (value: string) => {
  emit('update:password', value)
}
</script>

<template>
  <div class="relative flex w-screen flex-col items-center justify-center">
    <div class="relative mt-16 flex w-[30%] flex-col items-center gap-4 rounded-md border-2 border-gray-700 px-4 py-6 text-center text-white">
      <h1 class="text-2xl font-medium text-gray-700 uppercase">Login Page</h1>

      <!-- email field-->
      <div class="mx-auto flex w-[60%] flex-col gap-2">
        <label for="email" class="text-sm font-medium text-gray-700 underline">Email</label>
        <InputComponent
          :modelValue="email"
          @update:modelValue="updateEmail"
          class="rounded-full border-2 bg-gray-200 px-4 py-2 font-semibold text-gray-900 outline-none"
          id="email"
          label="Email"
          type="email"
          placeholder="Enter your email"
        />
      </div>

      <!-- password field-->
      <div class="mx-auto flex w-[60%] flex-col gap-2">
        <label for="password" class="text-sm font-medium text-gray-700 underline">Password</label>
        <InputComponent
          :modelValue="password"
          @update:modelValue="updatePassword"
          class="rounded-full border-2 bg-gray-200 px-4 py-2 font-semibold text-gray-900 outline-none"
          id="password"
          label="Password"
          type="password"
          placeholder="Enter your password"
        />
      </div>
      <div class="mb-5">
        <a href="#" class="font-medium text-gray-900 hover:underline">Forgot password? </a>
      </div>

      <!-- login button -->
      <ButtonComponent
        label="Login"
        :disabled="isLoading"
        class="relative mx-auto flex cursor-pointer flex-col gap-4 rounded-md border-2 bg-[#fcc61d] px-4 py-2 text-center text-xl text-gray-900 shadow-xl shadow-gray-400 transition-colors duration-300 hover:bg-yellow-500 sm:w-[150px] md:w-[200px]"
        @click="handleSubmit"
      />

      <!-- error message if something is wrong -->
      <div v-if="errorMessage" class="mt-2 text-sm font-bold text-red-500 select-none">
        {{ errorMessage }}
      </div>

      <!-- create account -->
      <p class="mt-4 text-sm font-medium text-gray-700">
        Not a user?
        <a href="/register" class="font-medium text-blue-600 hover:underline"> Create an account </a>
      </p>
    </div>
    <img :src="LoginImage" alt="Logo" class="-mt-25 w-auto items-center object-contain select-none" />
  </div>
</template>

// src/components/Login/login.tsx
import { useEffect, useState } from "react";
import { useAuthStore } from "../../store";
import { Button } from "../Button";
import { InputComponent } from "../Input";
import LoginImage from "/assets/images/login.jpg";
import { GotoRegisterComponent } from "./goto_register";
import { StatusMessageComponent } from "../StatusMessage";
import { ForgotPasswordComponent } from "./forgot_password";
import { useNavigate } from "react-router-dom";

export const LoginComponent = () => {
  const { login, isAuthenticated, isLoading, error } = useAuthStore();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [localError, setLocalError] = useState<string | null>(null);

  const navigate = useNavigate();
  useEffect(() => {
    if (isAuthenticated) {
      navigate("/dashboard", { replace: true });
    }
  }, [isAuthenticated, navigate]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setLocalError(null);

    if (!email || !password) {
      setLocalError("email and password are required");
      return;
    }

    await login({ email, password });
  }

  return (
    <div className="relative flex flex-col items-center justify-center">
      <div className="relative mt-16 flex w-[30%] flex-col items-center gap-4 rounded-md border-2 border-gray-700 px-4 py-6 text-center text-white">
        <h1 className="text-2xl font-medium text-gray-700 uppercase">
          Login Page
        </h1>

        <form onSubmit={handleSubmit} className="w-full flex flex-col gap-4">
          {/* email field */}
          <div className="mx-auto flex w-[60%] flex-col gap-2">
            <label
              htmlFor="email"
              className="text-sm font-medium text-gray-700 underline"
            >
              Email
            </label>
            <InputComponent
              value={email}
              onChange={setEmail}
              className="rounded-full border-2 bg-gray-200 px-4 py-2 font-semibold text-gray-900 outline-none"
              id="email"
              type="email"
              placeholder="Enter your email"
              required
            />
          </div>

          {/* password field */}
          <div className="mx-auto flex w-[60%] flex-col gap-2">
            <label
              htmlFor="password"
              className="text-sm font-medium text-gray-700 underline"
            >
              Password
            </label>
            <InputComponent
              value={password}
              onChange={setPassword}
              className="rounded-full border-2 bg-gray-200 px-4 py-2 font-semibold text-gray-900 outline-none"
              id="password"
              type="password"
              placeholder="Enter your password"
              required
            />
          </div>

          <ForgotPasswordComponent />

          {/* login button */}
          <Button
            type="submit"
            disabled={isLoading}
            label={isLoading ? "Logging In..." : "Login"}
            className={`relative mx-auto flex cursor-pointer flex-col gap-4 rounded-md border-2 bg-[#fcc61d] px-4 py-2 text-center text-xl text-gray-900 shadow-xl shadow-gray-400 transition-colors duration-300 hover:bg-yellow-500 sm:w-37.5 md:w-50 ${isLoading ? "cursor-not-allowed opacity-50" : ""}`}
          />
        </form>

        {(localError || error) && (
          <StatusMessageComponent message={localError || error} type="error" />
        )}

        <GotoRegisterComponent />
      </div>

      <img
        src={LoginImage}
        alt="Logo"
        className="-mt-25 w-auto items-center object-contain select-none"
      />
    </div>
  );
};
